version: '3'

services:

  postgres:
    image: postgres:12
    ports:
      - 5433:5432
    volumes:
      - ~/apps/organono-backend/pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=organono_backend
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin

  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=organono
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=organono_backend
      - RABBITMQ_ERLANG_COOKIE=QAHpw0kjARdWvwp

  organono-api:
    image: vonmutinda/organono:v1.0.0
    ports:
      - 8080:5050
    depends_on:
      - postgres
    volumes:
      - ~/apps/organono:/var/log/organono-api  
    environment:
      - DATABASE_URL=postgres://admin:password@${DOCKER_GATEWAY_HOST:-host.docker.internal}:5433/organono_backend?sslmode=disable
      - ENVIRONMENT=development
      - LOG_FILE=""
      - PORT=8080
